import time

def one_test():
    print('start test')
    time.sleep(5)
    print('5 seconds')
    time.sleep(5)
    print('10 seconds')
    time.sleep(5)
    print('15 seconds')
    time.sleep(5)
    print('20 seconds')
    time.sleep(5)
    print('25 seconds')

def two_test():
    print('start test')
    time.sleep(5)
    print('5 seconds')
    time.sleep(5)
    print('10 seconds')
    time.sleep(5)
    print('15 seconds')
    time.sleep(5)
    print('20 seconds')
    time.sleep(5)
    print('25 seconds')

def three_test():
    print('start test')
    time.sleep(5)
    print('5 seconds')
    time.sleep(5)
    print('10 seconds')
    time.sleep(5)
    print('15 seconds')
    time.sleep(5)
    print('20 seconds')
    time.sleep(5)
    print('25 seconds')